name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    strategy:
      matrix:
        language: [python, dotnet]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      if: matrix.language == 'python'
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      if: matrix.language == 'python'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python tests
      if: matrix.language == 'python'
      run: |
        pytest

    - name: Set up .NET Core
      if: matrix.language == 'dotnet'
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Install .NET dependencies
      if: matrix.language == 'dotnet'
      run: dotnet restore

    - name: Build .NET project
      if: matrix.language == 'dotnet'
      run: dotnet build --no-restore

    - name: Run .NET tests
      if: matrix.language == 'dotnet'
      run: dotnet test --no-build --verbosity normal